services:
  api-invoice:
    image: sooyaa1/invoice-erpapi:v1
    container_name: fastapi-invoice-api
    ports:
      - "8002:8000"
    environment:
      # เชื่อมต่อไปยัง Hostname 'postgres-db'
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/hrdb
      - API_KEY=chosy-secret-key-2026
    # ต้องระบุ network เดียวกับที่ postgres-db รันอยู่
    networks:
      - erp-network
    restart: unless-stopped

networks:
  # กำหนดให้ใช้ network ร่วมกัน (External)
  erp-network:
    external: true